require("../node_modules/uupaa.extend.js/lib/Extend.js");
require("../../WebModule/lib/Console.js");
require("../../WebModule/lib/Help.js");
require("../../WebModule/lib/Valid.js");
require("../../WebModule/lib/TestTask.js");
require("../../WebModule/lib/Test.js");
require("../lib/Ruby.js");
require("../release/Ruby.min.js");
require("./testcase.js");
